name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_study_jam: ^0.2.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  chat_bubbles: ^1.3.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true
